# fly.toml app configuration file generated for spike on 2025-02-01T14:03:50+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spike'
primary_region = 'sin'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = "always"
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
